bookletName: BOOKLET.SAMPLE-1
auth:
  name: test-no-pw
  password: ''
UNIT_URLS:
  - UNIT.SAMPLE
  - UNIT.SAMPLE-2
  - UNIT.SAMPLE
RESOURCE_FILES:
  - SAMPLE_UNITCONTENTS.HTM?v=f
  - SAMPLE_UNITCONTENTS.HTM?v=f
  - VERONA-PLAYER-SIMPLE-4.0.html?v=1
