#bookletName: BOOKLET.SAMPLE-1
bookletName: 'BOOKLETV8HT2022ENGTHA'
auth:
#  name: test-no-pw
#  password: ''
  name: lasttest.gross01.mit
  password: last
#FILE_LIST:
#  - /api/test/{}/resource/IQB-PLAYER-ASPECT@1.15.HTML?v=1
#  - /api/test/{}/resource/ESinfoLaender.voud?v=f
#  - /api/test/{}/resource/ESLHstart.voud?v=f
#  - /api/test/{}/resource/ESbspMC-Gif.voud?v=f
#  - /api/test/{}/resource/ESbspSA-Gif.voud?v=f
#  - /api/test/{}/resource/ESLbspMM-DaD-Gif.voud?v=f
#  - /api/test/{}/resource/ESbspCMC-Gif.voud?v=f
#  - /api/test/{}/resource/ESHaudioerklaerung.voud?v=f
#  - /api/test/{}/resource/ESHinst.voud?v=f
#  - /api/test/{}/resource/EL614.voud?v=f
#  - /api/test/{}/resource/EL643.voud?v=f
#  - /api/test/{}/resource/EL602.voud?v=f
#  - /api/test/{}/resource/EL595.voud?v=f
#  - /api/test/{}/resource/EL596.voud?v=f
#  - /api/test/{}/resource/ESLinst-Gif.voud?v=f
#  - /api/test/{}/resource/ER554.voud?v=f
#  - /api/test/{}/resource/ER543.voud?v=f
#  - /api/test/{}/resource/ER533.voud?v=f
#  - /api/test/{}/resource/ESHwart.voud?v=f
#  - /api/test/{}/resource/EL619.voud?v=f
#  - /api/test/{}/resource/EL617.voud?v=f
#  - /api/test/{}/resource/EL615.voud?v=f
#  - /api/test/{}/resource/EL612.voud?v=f
#  - /api/test/{}/resource/ESHaudioende.voud?v=f
#  - /api/test/{}/resource/ESLwart.voud?v=f
#  - /api/test/{}/resource/ER547.voud?v=f
#  - /api/test/{}/resource/ER512.voud?v=f
#  - /api/test/{}/resource/ER552.voud?v=f
#  - /api/test/{}/resource/ER542.voud?v=f
#  - /api/test/{}/resource/ESHLende.voud?v=f
#FILE_LIST:
#  - /api/test/{}/unit/UNIT.SAMPLE/alias/UNIT.SAMPLE
#  - /api/test/{}/unit/UNIT.SAMPLE-2/alias/UNIT.SAMPLE-2
#  - /api/test/{}/unit/UNIT.SAMPLE/alias/an_alias
#  - /api/test/{}/resource/SAMPLE_UNITCONTENTS.HTM?v=f
#  - /api/test/{}/resource/SAMPLE_UNITCONTENTS.HTM?v=f
#  - /api/test/{}/resource/VERONA-PLAYER-SIMPLE-4.0.HTML?v=1
UNIT_URLS:
  - ESINFOLAENDER/alias/ESINFOLAENDER
  - ESLHSTART/alias/ESLHSTART
  - ESBSPMC-GIF/alias/ESBSPMC-GIF
  - ESBSPSA-GIF/alias/ESBSPSA-GIF
  - ESLBSPMM-DAD-GIF/alias/ESLBSPMM-DAD-GIF
  - ESBSPCMC-GIF/alias/ESBSPCMC-GIF
  - ESHAUDIOERKLAERUNG/alias/ESHAUDIOERKLAERUNG
  - ESHINST/alias/ESHINST
  - EL614/alias/EL614
  - EL643/alias/EL643
  - EL602/alias/EL602
  - EL595/alias/EL595
  - EL596/alias/EL596
  - ESLINST-GIF/alias/ESLINST-GIF
  - ER554/alias/ER554
  - ER543/alias/ER543
  - ER533/alias/ER533
  - ESHWART/alias/ESHWART
  - EL619/alias/EL619
  - EL617/alias/EL617
  - EL615/alias/EL615
  - EL612/alias/EL612
  - ESHAUDIOENDE/alias/ESHAUDIOENDE
  - ESLWART/alias/ESLWART
  - ER547/alias/ER547
  - ER512/alias/ER512
  - ER552/alias/ER552
  - ER542/alias/ER542
  - ESHLENDE/alias/ESHLENDE
RESOURCE_FILES:
#  - IQB-PLAYER-ASPECT@1.15.HTML
  - iqb-player-aspect@1.15.html
  - ESinfoLaender.voud
  - ESLHstart.voud
  - ESbspMC-Gif.voud
  - ESbspSA-Gif.voud
  - ESLbspMM-DaD-Gif.voud
  - ESbspCMC-Gif.voud
  - ESHaudioerklaerung.voud
  - ESHinst.voud
  - EL614.voud
  - EL643.voud
  - EL602.voud
  - EL595.voud
  - EL596.voud
  - ESLinst-Gif.voud
  - ER554.voud
  - ER543.voud
  - ER533.voud
  - ESHwart.voud
  - EL619.voud
  - EL617.voud
  - EL615.voud
  - EL612.voud
  - ESHaudioende.voud
  - ESLwart.voud
  - ER547.voud
  - ER512.voud
  - ER552.voud
  - ER542.voud
  - ESHLende.voud
